### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by mhusainisurge** [Odonno/ReduxSimple#12]
Add unit tests to make sure the code functions as expected and continues to do so as it evolves.

**Comment by Odonno** [comment]
We should do Rx testing 

http://www.introtorx.com/content/v1.0.10621.0/16_TestingRx.html

**Comment by Odonno** [comment]
Well, well. We were close to perfections. :)

https://github.com/Odonno/ReduxSimple/blob/b28af367dbe11c8ebccd428f1459ed33010a8c8a/ReduxSimple/ReduxStoreWithHistory.cs#L82

I implemented all unit tests with xUnit and one test failed on `Redo` function. Indeed, unit tests was necessary.

**Comment by mhusainisurge** [comment]
This is great!
