### ISSUE TITLE
Create logo

### ISSUE THREAD

**Issue by Odonno** [Odonno/ReduxSimple#19]

**Comment by Odonno** [comment]
@mhusainisurge I added a logo o nthe readme page. What do you think?


If it's okay, I will update the nuget feed to use this image as the nuget icon.

**Comment by mhusainisurge** [comment]
The logo looks pretty good to me. Seems like it's inspired by the Redux logo, but is there any further meaning behind it?

**Comment by Odonno** [comment]
Yes, I was inspired by the Redux logo. That's it. I also wanted to make a simple logo based on the name of the repository.

Another inspiration was the Flux capacitor in Back to the Future. I can make it look more like this image:

![](https://vignette.wikia.nocookie.net/bttf/images/6/64/Flux-Capacitor.jpg/revision/latest?cb=20080602215902)

**Comment by mhusainisurge** [comment]
Nice BttF reference. Yeah, it's good either way.

**Comment by Odonno** [comment]
Well, I made a new logo. IMO, it is much much better than the previous one. I have also added some "Fluent" design system touch, a blur/neon-like effect.

I close issue now. Will update NuGet icon once 1.2 is ready for release.
