### ISSUE TITLE
Possibility of State Composition

### ISSUE THREAD

**Issue by julianpaulozzi** [Odonno/ReduxSimple#41]
It would be possible to somehow define state composition to facilitate the maintenance of large state trees?

Something like ngrx [Feature Module State Composition](https://github.com/ngrx/platform/blob/master/docs/store/api.md#feature-module-state-composition).

The idea would be to keep a single store but compose the pair (state -> reductor) in several parts.

**Comment by Odonno** [comment]
Hi @julianpaulozzi 

I am not sure to understand this feature very well for now. What you wish is to compose the state? If so then I don't see why you cannot do it using Observable?

**Comment by Odonno** [comment]
@julianpaulozzi I think I needed to play more with the @ngrx package with bigger projects and indeed, there are some valuable features. If you are still interested, ReduxSimple is now in v3 with some exciting features like:

* reducers with the `On` pattern from @ngrx and the ability to create sub/nested reducers
* my discovery of the year: selectors (memoized selectors, memoized selectors with props, combined selectors)
* and some other features currently in preview (Router Store, DevTools)

So, you can now compose your state in different parts and create as much features/nested state as you want. You can also check the readme file which described the new features pretty well.

**Comment by julianpaulozzi** [comment]
That sounds great, when you have the opportunity I will check.
Good work, thanks.
