### ISSUE TITLE
Why do you use "where T : class" in ObserveAction<T>?

### ISSUE THREAD

**Issue by MihailsKuzmins** [Odonno/ReduxSimple#45]
According to System.Reactive.Linq, the extension method OfType<TResult> has no bounds - it can be of any type. So, is there any specific reason why you use "where T : class" in the ObserveAction<T> functions where the only generic part is OfType<T> ?

For example, it prevents using struct, or enum as action. Maybe you intended to use action only as a reference type and not as a struct, enum, etc. Just want to know. Thanks

**Comment by Odonno** [comment]
@MihailsKuzmins Good point. It is strongly impacted by the way I write my applications with this library/pattern.

But it makes sense to not only use class but also (readonly?) struct. I am not really sure if enum is a viable option but it can be another solution.

I will fix this that.

**Comment by Odonno** [comment]
@MihailsKuzmins Done. You will soon see the new package version here : https://www.nuget.org/packages/ReduxSimple/2.0.1

I hope you'll like it.

**Comment by MihailsKuzmins** [comment]
@Odonno thank you :)
