### ISSUE TITLE
Build Failed: namespace Windows.UI.Xaml.Navigation not found

### ISSUE THREAD

**Issue by wizd** [Odonno/ReduxSimple#69]
Windows: Version 10.0.18362.535
Visual Studio 2019: Version 16.4.2

detailed log here:

`4>------ Build started: Project: ReduxSimple.Uwp.DevTools, Configuration: Debug Any CPU ------
2>C:\Program Files\dotnet\sdk\3.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets(256,5): warning NETSDK1023: A PackageReference for 'Microsoft.NETCore.UniversalWindowsPlatform' was included in your project. This package is implicitly referenced by the .NET SDK and you do not typically need to reference it from your project. For more information, see https://aka.ms/sdkimplicitrefs
2>RouterEvents.cs(2,23,2,33): error CS0234: The type or namespace name 'Navigation' does not exist in the namespace 'Windows.UI.Xaml' (are you missing an assembly reference?)
2>RouterEvents.cs(24,16,24,30): error CS0246: The type or namespace name 'NavigationMode' could not be found (are you missing a using directive or an assembly reference?)
2>RouterEvents.cs(46,16,46,30): error CS0246: The type or namespace name 'NavigationMode' could not be found (are you missing a using directive or an assembly reference?)
2>RouterEvents.cs(12,16,12,30): error CS0246: The type or namespace name 'NavigationMode' could not be found (are you missing a using directive or an assembly reference?)
2>RouterStoreExtensions.cs(20,87,20,92): error CS0246: The type or namespace name 'Frame' could not be found (are you missing a using directive or an assembly reference?)
2>Done building project "ReduxSimple.Uwp.RouterStore.csproj" -- FAILED.
`

**Comment by Odonno** [comment]
Hi @wizd 

It looks like you lack some dependencies. It seems you are using the 3.0.101 of dotnet core, I was using the 2.2. I will upgrade to see if it changes anything.

**Comment by Odonno** [comment]
Can you check you have installed the SDK 16299?

**Comment by Odonno** [comment]
@wizd Sorry. I did not checked on you earlier. Did you manage to make it work?

**Comment by wizd** [comment]
hello, It's all good now with .net core 3.1. thank you.

**Comment by Odonno** [comment]
Good to know.
