### ISSUE TITLE
On function new() constraint does not play nicely with immutables

### ISSUE THREAD

**Issue by kobi2294** [Odonno/ReduxSimple#70]
When using ReduxSimple.Reducers.On methods, they all require TState that has a new() - default parameterless constructor. In my project, I am using immutable classes that have readonly properties and a constructor that takes all the properties as parameters, so there is no parameterless constructor. Why should this be a constraint?

**Comment by Odonno** [comment]
Hi @kobi2294 I think it may be a legacy constraint from the previous versions of ReduxSimple. I will fix that and let you know when the new version is available.

**Comment by Odonno** [comment]
The v3.0.1 will be available soon.
