### ISSUE TITLE
Next version with current state

### ISSUE THREAD

**Issue by rubiktubik** [Odonno/ReduxSimple#79]
Hello,

i have noticed that the master branch uses other Methods in the example app such
`CombineReducers` as in version 3.4.

When is the next release planned?

**Comment by Odonno** [comment]
Hi @rubiktubik I am working on a `UntilDestroyed` operator. Next version coming really soon. 

I will let you know.

**Comment by Odonno** [comment]
Done. v3.5 is now available. 

Feel free to ask a question if you have a problem.

Thank you.

**Comment by rubiktubik** [comment]
Thank you! Very cool project!
