### ISSUE TITLE
There is an ArgumentException on RemoveAll entity adapter method invocation.

### ISSUE THREAD

**Issue by p1eXu5** [Odonno/ReduxSimple#93]
There is an ArgumentException on RemoveAll entity adapter method invocation. 

In the current version:

```csharp
public TEntityState RemoveAll<TEntityState>(TEntityState state)
    where TEntityState : EntityState<TEntity, TKey>
{
    var collection = new Dictionary<TEntity, TKey>();
    return state.With(new
    {
        Ids = collection.Keys.ToList(),
        Collection = collection
    });
}
```

To fix this the dictionary parameters should be inverted: 
```csharp 
...
var collection = new Dictionary<TKey, TEntity>(); 
...
```

**Comment by Odonno** [comment]
Well, I am not sure why I kept the `<TEntity, TKey>` in that order. I will invert this order to be logical. Note that there will be a small breaking change then.

**Comment by Odonno** [comment]
Fixed. You should the v3.6.1-preview002 in a few minutes.

Enjoy!
